spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://ifn636server.mysql.database.azure.com:3306/ifn636_db?useSSL=true&serverTimezone=UTC
    username: ifn636admin
    password: 123321qq!
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

app:
  jwt:
    secret: "IFN636LoginSecretKey-SOWJFNA$SJf"
    expire-minutes: 120

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
